name: "Terraform Deploy"
description: "Run terraform apply"
inputs:
  env:
    description: "Environment to deploy to"
    required: true
  directory:
    description: "Terraform directory to deploy from"
    required: true

runs:
  using: "composite"

  steps:
    - name: terraform init
      run: terraform init
      shell: bash
      working-directory: ./terraform/${{ inputs.directory }}
    - name: terraform workspace
      run: terraform workspace new ${{ inputs.env }}
      shell: bash
      working-directory: ./terraform/${{ inputs.directory }}
    - name: terraform apply
      run: terraform apply -auto-approve -lock-timeout=30m
      shell: bash
      working-directory: ./terraform/${{ inputs.directory }}
